apiVersion: apps/v1
kind: Deployment
metadata:
  name: darkweb
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: darkweb
  template:
    metadata:
      labels:
        app: darkweb
    spec:
      containers:
      - name: darkweb
        image: squat/darkweb
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 5
        ports:
        - containerPort: 8080
        resources:
          limits:
            nvidia.com/gpu: 1
      tolerations:
      - key: nvidia.com/gpu
        effect: NoSchedule
        operator: Exists
